export const PROVINCES = [
  "bulawayo",
  "harare",
  "manicaland",
  "mashonaland_central",
  "mashonaland_east",
  "mashonaland_west",
  "masvingo",
  "matabeleland_north",
  "matabeleland_south",
  "midlands",
] as const;

export type Province = (typeof PROVINCES)[number];

export const PROVINCE_LABELS: Record<Province, string> = {
  bulawayo: "Bulawayo",
  harare: "Harare",
  manicaland: "Manicaland",
  mashonaland_central: "Mashonaland Central",
  mashonaland_east: "Mashonaland East",
  mashonaland_west: "Mashonaland West",
  masvingo: "Masvingo",
  matabeleland_north: "Matabeleland North",
  matabeleland_south: "Matabeleland South",
  midlands: "Midlands",
};

export const DISTRICTS_BY_PROVINCE: Record<Province, readonly string[]> = {
  bulawayo: ["Bulawayo"],
  harare: ["Harare", "Chitungwiza", "Epworth"],
  manicaland: [
    "Buhera",
    "Chimanimani",
    "Chipinge",
    "Makoni",
    "Mutare",
    "Mutasa",
    "Nyanga",
  ],
  mashonaland_central: [
    "Bindura",
    "Centenary",
    "Guruve",
    "Mazowe",
    "Mbire",
    "Mount Darwin",
    "Muzarabani",
    "Rushinga",
    "Shamva",
  ],
  mashonaland_east: [
    "Chikomba",
    "Goromonzi",
    "Marondera",
    "Mudzi",
    "Murehwa",
    "Mutoko",
    "Seke",
    "UMP",
    "Wedza",
  ],
  mashonaland_west: [
    "Chegutu",
    "Hurungwe",
    "Kariba",
    "Makonde",
    "Mhondoro-Ngezi",
    "Sanyati",
    "Zvimba",
  ],
  masvingo: [
    "Bikita",
    "Chiredzi",
    "Chivi",
    "Gutu",
    "Masvingo",
    "Mwenezi",
    "Zaka",
  ],
  matabeleland_north: [
    "Binga",
    "Bubi",
    "Hwange",
    "Lupane",
    "Nkayi",
    "Tsholotsho",
    "Umguza",
  ],
  matabeleland_south: [
    "Beitbridge",
    "Bulilima",
    "Gwanda",
    "Insiza",
    "Mangwe",
    "Matobo",
    "Umzingwane",
  ],
  midlands: [
    "Chirumhanzu",
    "Gokwe North",
    "Gokwe South",
    "Gweru",
    "Kwekwe",
    "Mberengwa",
    "Shurugwi",
    "Zvishavane",
  ],
};
